name: devfest_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.5
  equatable: ^2.0.5
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_remote_config: ^5.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.14
  google_generative_ai: ^0.4.6
  google_sign_in: ^6.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
