// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUwWWuEC9X_hoefFy7Kjre8nKN6S3_kyw',
    appId: '1:727475414374:web:d31343957475812e1c14a7',
    messagingSenderId: '727475414374',
    projectId: 'public-chat-b906a',
    authDomain: 'public-chat-b906a.firebaseapp.com',
    storageBucket: 'public-chat-b906a.appspot.com',
    measurementId: 'G-40Q4GGVSXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPzyoHS5Lr5H4wJOAtEb-LQcwP-JguBXQ',
    appId: '1:727475414374:android:42088e59fb760fc01c14a7',
    messagingSenderId: '727475414374',
    projectId: 'public-chat-b906a',
    storageBucket: 'public-chat-b906a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXPTGTfmcZ2LXrpxFUHm5A8qFxo-mv2Dc',
    appId: '1:727475414374:ios:cfe88c32f9cb1d7a1c14a7',
    messagingSenderId: '727475414374',
    projectId: 'public-chat-b906a',
    storageBucket: 'public-chat-b906a.appspot.com',
    androidClientId: '727475414374-5fho65r4k644fqt9541c7c1cgr7ddf3h.apps.googleusercontent.com',
    iosClientId: '727475414374-380orqdfeqjcs28rra5tnip5np195otj.apps.googleusercontent.com',
    iosBundleId: 'com.example.devfestChat',
  );
}
