// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVllEgr5fKtGPfP6OKEa4ZpqqLE1vQBxw',
    appId: '1:727475414374:web:cd381c35a14926671c14a7',
    messagingSenderId: '727475414374',
    projectId: 'public-chat-b906a',
    authDomain: 'public-chat-b906a.firebaseapp.com',
    storageBucket: 'public-chat-b906a.appspot.com',
    measurementId: 'G-0KHTW7F6EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbd9IaqAwkh0BunJJn5cwkVRr0q-eN5dQ',
    appId: '1:727475414374:android:96ac6fe8da0705fd1c14a7',
    messagingSenderId: '727475414374',
    projectId: 'public-chat-b906a',
    storageBucket: 'public-chat-b906a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOYdDCuaeGRpfjbL5WTXuPXmh9JqE5epM',
    appId: '1:727475414374:ios:28b138f3996a7de91c14a7',
    messagingSenderId: '727475414374',
    projectId: 'public-chat-b906a',
    storageBucket: 'public-chat-b906a.appspot.com',
    androidClientId: '727475414374-g8j3vpncs2kdcv1nh2f5shsnlcuth2tg.apps.googleusercontent.com',
    iosClientId: '727475414374-64rhrjc5c05qj6ou04bd58ppc4s7qht0.apps.googleusercontent.com',
    iosBundleId: 'com.example.devfestChat',
  );
}
